<h1> Numpy

1. Numpy stand for Numerical(Num) Python(py)
2. It is written in python, c and c++
3. It also has some function for working in domain of linear algebra, fourier transform and matrix. Generally used for working with array's in python
4. Numpy is faster than list

In [2]:
import numpy as np    # python alias are alternate name for reffering to the same thing. create alias with 'as' keyword.

l = [4,5,6,7]
# create array with array("pass either tuple or list") function
a = np.array(l)   # pass list in array()function 
a

array([4, 5, 6, 7])

 The array onject's in numpy is called ndarray. and type is numpy.ndarray

In [4]:
type(a)

numpy.ndarray

#### Dimensions in array

1. #### Zero- dimension:
                it contain only one element like (np.array(42))
2. #### One- dimension:  
                it contain Zero-dimesion element like (np.array([42,56,32]))
3. #### Two- dimension:  
                it contain one- dimension element like (np.array([[ 42,56,32],[23,56,82]]))
4. #### Three- dimension:
                it contain two- dimension element like (np.array([[[ 42,56,32],[23,56,82]],[[1,2,3],[4,5,6]]]))
______________________________

##### 'ndim( )' function return as integer that tells us how many dimension the array have
#####  You can also define the number of dimension's by using the 'ndmin' argument

In [7]:
a = np.array([[4,5,6],[6,8,9],[12,7,4]])                #create a 2 dimension array
print(a)
a.ndim     

[[ 4  5  6]
 [ 6  8  9]
 [12  7  4]]


2

In [9]:
a = np.array([1,2,3,4],ndmin=5)       # using 'ndmin' we make array 'a' 5 dimension
a.ndim                     

5

#### Dtype:
1. return the data type of array
2. we can also creat an array with define data type

In [10]:
a = np.array([[4,5,6],[6,8,9],[12,7,4]]) 
a.dtype

dtype('int32')

In [11]:
a = np.array([[4,5,6],[6,8,9],[12,7,4]],dtype='int64')
a.dtype

dtype('int64')

#### Acces array element's
Access elements with the help of index in square braket[] as like as list,string in python. 

In [14]:
arr = np.array([1,2,3,4])
print(arr[0])
print(arr[1:3])

1
[2 3]


In [20]:
# how to access in two dimension
a = np.array([[4,5,6],[6,8,9],[12,7,4]])
print(a)
print(a[1,2])                        # a['index of row', 'column']
print(a[2])                          # access complete row
a[0,1:]                               # access a part of row

[[ 4  5  6]
 [ 6  8  9]
 [12  7  4]]
9
[12  7  4]


array([5, 6])

#### Numpy array copy and view
when we change in copy no change in orignal but if we change in view also change orignal

In [38]:
a =  np.array([1,2,3,4])
b =  np.array([5,6,7,8])
x = a.copy()                 # x is the copy of a
y = b.view()                 # y is the view of b

In [40]:
print(x)
print(y)
# base() function is used to check the array it copy or view
# if copy the it show none other wise refelct the orignal array
print(x.base)
print(y.base)

[1 2 3 4]
[5 6 7 8]
None
[5 6 7 8]


#### Shape:

In [41]:
arr =  np.array([[1,2,3],[4,5,6]])
np.shape(arr)
# return a tuple (2,3) which means array has 2 dimension and 3 elements in each.

(2, 3)

In [43]:
arr =  np.array([1,2,3,4], ndmin=5)
np.shape(arr)
# return a tuple (1,1,1,1,4) which means array has 5 dimension and In 1 to 4 dimension has 1 elements in each. and 4 element in last dimension(5th)

(1, 1, 1, 1, 4)

#### Reshape:
we can change the number of elements in each dimension or add or remove dimension.

In [67]:
arr1 =  np.array([[1,2,3,7],[4,5,6,8]])
# re-shape arr1
arr1.reshape(4,2)

array([[1, 2],
       [3, 7],
       [4, 5],
       [6, 8]])

In [68]:
print(np.shape(arr1))
# 'arr1' not change because 'rehape make a copy'
arr1 = arr1.reshape(4,2)
np.shape(arr1)

(2, 4)


(4, 2)

In [69]:
# np.ravel(arr1) 
#     or
arr1.reshape(-1)
# both change the array inot 1 - dimension

array([1, 2, 3, 7, 4, 5, 6, 8])

#### Iterating:
mean's going through element one by one

In [71]:
arr =np.array([[1,2,3,4],[5,6,7,8]])
for i in arr:
    for j in i:
        print(j)
# it is difficult to when array is multi dimensional

1
2
3
4
5
6
7
8


In [72]:
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8


In [73]:
for i, j in np.ndenumerate(arr):
    print(i,j) 

# i: repersent index and j repersent element 

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


#### Numpy Splitting Array:

In [74]:
arr =np.array([1,2,3,4,5,6,7,8])
np.array_split(arr,3)   # split the arry in three arrys

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]

#### Searching in array

In [77]:
a = np.array([2,3,9,6,5,4,2,1,12,13,15,19,56])
# search all elemnts which is divide by 2
print(np.where(a%2==0))
# it return index of the element which fill the condition

(array([ 0,  3,  5,  6,  8, 12], dtype=int64),)


In [81]:
a = np.array([2,3,9,6,5,4,2,1,12,13,15,19,56])
x = np.searchsorted(a,56)            # search single element 
y = np.searchsorted(a,[1,2,3])        # search multiple elements by passing a list
print(x)          
print(y)

12
[0 0 8]


#### Numpy filter array:
Getting some elements out of an array and creating a new array out of them

In [84]:
arr = np.array([41,42,43,44])
x =[False,True,False,True]
new_arr =arr[x]
new_arr

array([42, 44])

In [86]:
arr = np.array([41,42,43,44])
# creat an empty list
x = []
for i in arr:
    if i%2 ==0:
        x.append(True)
    else:
        x.append(False)
print(x)
new_arr = arr[x]
new_arr

[False, True, False, True]


array([42, 44])

Creating filter directly from an array

In [87]:
arr = np.array([41,42,43,44])
filter_arr = arr%2 ==0
new_arr = arr[filter_arr]
new_arr

array([42, 44])

<h1>Thank you