<h1> Numpy

#### Some basic math's

In [48]:
import numpy as np
x = np.array([2,9,32,56,7,66,6,7,22,4,5,5,56,48,56])
np.mean(x)

25.4

In [49]:
print(np.median(x))
print(np.std(x))

9.0
23.357511282954217


In [42]:
print(x.max())
print(x.min())

66
2


In [47]:
# use some basic math's
y = np.array([1,2,1,3])
print(y*2)
print(y+5)

[2 4 2 6]
[6 7 6 8]


#### Create some arrays using inbuild functions

In [51]:
# create a array with zeros
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [52]:
# create a array with a same element
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [55]:
# ceate a indentity matrix
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [57]:
# create an array with all elements are 1
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [58]:
# generate a array using 'arange()' function like a 'range()' 
np.arange(11,50,2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49])

#### Add two arrays:

In [63]:
x = np.array([[1,0],[0,1]])
y = np.array([[3,3],[3,3]])
np.sum((x,y),axis=0)

array([[4, 3],
       [3, 4]])

#### Dot Product
same as matric's and use same rules

In [64]:
x = np.array([[1,2,3],[4,5,6]])
y =  np.array([[7,8],[9,10],[11,12]])
z = np.dot(x,y)
z

array([[ 58,  64],
       [139, 154]])

#### join array's in numpy

In [37]:

a =  np.array([1,2,3,4])
b =  np.array([5,6,7,8])
# join upper two arrys using concatenate() function
np.concatenate((a,b), axis=0)    # by default axis is 0(row)

# the dimension of  output array is same as input  array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
a =  np.reshape(a,(2,2))
b = np.reshape(b,(2,2))
np.concatenate((a,b), axis=1)

# the dimension of  output array is same as input  array

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [11]:
a =  np.array([1,2,3,4])
b =  np.array([5,6,7,8])
np.stack((a,b),axis=1)

# the dimension of  output array is not same as the input  array

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [14]:
a =  np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.stack((a,b))      # by default axis = 0

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [16]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [17]:
 np.dstack((a,b))

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

<h1>  Numpy Random:

##### Random number doesn't means a different number everytime. Random means something that can't be predicted logically. There must be some algrothim to generate the random number it means the number is not true random

Generate a random number:-

In [34]:
from numpy import random
x =  random.random()       # it give a random number
x

0.8269792800143697

In [31]:
x =  random.randint(100)         # it give a random number(int) in between 0 to 100
x

53

In [21]:
# Generate a random array by giving the size and the range of random number number
x = random.randint(2,9,size=(2,2))
x

array([[2, 6],
       [5, 8]])

In [22]:
# create a random array with 'rand(size())' 
x = random.rand(5)
x

array([0.32324237, 0.53108366, 0.7285017 , 0.67963497, 0.0235267 ])

In [23]:
# create a random array with 'rand(size())' 
x = random.rand(3,5)
x

array([[7.66136184e-01, 6.62792239e-01, 5.61701589e-02, 6.76528185e-01,
        8.81650148e-05],
       [2.92207833e-01, 3.96333854e-01, 2.85881055e-01, 8.70889428e-01,
        4.39857556e-01],
       [4.53497845e-01, 5.36465239e-01, 7.86588608e-01, 1.83769813e-01,
        3.61573349e-01]])

#### Generate a random array with an array

In [25]:
# create a random number with 'choice()' 
x = random.choice([2,9,6,7])
x               # x is always from in the list

7

In [30]:
# create a random array with 'choice([inter],size=)' 
x = random.choice([2,9,6,7],size=(4,4))
x               # x elements is always from in the list

array([[7, 7, 7, 2],
       [2, 6, 6, 7],
       [7, 6, 9, 2],
       [7, 6, 2, 2]])

#### Generate a random array with the elements problity. 

In [35]:
l = [5,7,1,8]
x =  random.choice(l,p=[0.25,0.5,0.15,0.1],size=(4,5)) # the probality with respect to items of list(l). Make sure the sum of (p) not more than 1
x

array([[1, 7, 7, 7, 5],
       [5, 1, 7, 5, 7],
       [1, 5, 1, 8, 1],
       [7, 5, 7, 5, 1]])

In [69]:
# some other arthmetics operation
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
np.add(x,y)
np.subtract(x,y)
np.multiply(x,y)
np.divide(x,y)
np.power(x,y)

array([[    1,    64],
       [ 2187, 65536]], dtype=int32)

In [70]:
# round the demical
# around("number", 'digit up to round')
a = np.around(3.16666666,2)
a

3.17

## Thank you